export type ContentType = 'educational' | 'motivational' | 'tutorial' | 'storytelling' | 'business' | 'lifestyle' | 'tips' | 'personal';
export type ContentFormat = 'feed' | 'stories' | 'reels';
export type CallToAction = 'follow' | 'link_bio' | 'comment' | 'share' | 'save' | 'dm' | 'tag_friends' | 'custom';
export type CopywritingFramework = 'aida' | 'pas' | 'before_after_bridge' | 'problem_solution' | 'storytelling' | 'listicle';

export interface CarouselData {
  title?: string;
  username: string; // Display name (e.g., "Lucas Freitas")
  instagramHandle: string;
  isVerified: boolean;
  content: string;
  slideCount: number; // Number of slides to generate (1-10)
  contentType: ContentType;
  contentFormat: ContentFormat;
  callToAction: CallToAction;
  customCTA?: string;
  copywritingFramework: CopywritingFramework;
  targetAudience?: string; // Auto-detected or user-specified
  profileImage?: File;
  slides?: Slide[];
  caption?: string;
  hashtags?: string[];
}

export interface Slide {
  id: number;
  text: string;
  isEdited: boolean;
  originalText: string;
  needsImage?: boolean; // Whether this slide would benefit from an image
  imagePrompt?: string; // AI-generated prompt for image creation
  imageUrl?: string; // Legacy - URL da imagem gerada (deprecated)
  contentImageUrls?: string[]; // Multiple content images generated by AI
  profileImageUrl?: string; // URL da imagem de perfil
}

export interface GeneratedSlides {
  slides: Slide[];
  caption: string;
  hashtags: string[];
}

export type Step = 1 | 2 | 3 | 4 | 5 | 6;

export interface StepProps {
  data: CarouselData;
  onNext: (updatedData: Partial<CarouselData>) => void;
  onBack: () => void;
}