export interface CarouselData {
  title?: string;
  username: string; // Display name (e.g., "Lucas Freitas")
  instagramHandle: string;
  isVerified: boolean;
  content: string;
  slideCount: number; // Number of slides to generate (1-10)
  profileImage?: File;
  slides?: Slide[];
  caption?: string;
  hashtags?: string[];
  openaiApiKey?: string;
}

export interface Slide {
  id: number;
  text: string;
  isEdited: boolean;
  originalText: string;
  needsImage?: boolean; // Whether this slide would benefit from an image
  imagePrompt?: string; // AI-generated prompt for image creation
  imageUrl?: string; // Legacy - URL da imagem gerada (deprecated)
  contentImageUrls?: string[]; // Multiple content images generated by AI
  profileImageUrl?: string; // URL da imagem de perfil
}

export interface GeneratedSlides {
  slides: Slide[];
  caption: string;
  hashtags: string[];
}

export type Step = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export interface StepProps {
  data: CarouselData;
  onNext: (updatedData: Partial<CarouselData>) => void;
  onBack: () => void;
}